# Generated by Django 5.0.2 on 2024-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_loan_id_alter_loan_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_repayment',
            new_name='monthly_installment',
        ),
    ]
